version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    command: npm start
    volumes:
      - ./backend:/app 
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    